services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mount/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z
      - ./mount/certs:/mosquitto/certs:Z

