services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mount/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z
